/**
 * Outbox events that never leave the platform as webhooks (M6.3b), each with the reason. Together
 * with the catalog's `source` keys this classifies every outbox event: `catalog.test.ts` scans the
 * code for emitted and subscribed `type@version` keys and fails on any that is in neither list, so
 * a new event is a deliberate public-or-not decision. Promoting one later is additive: add a
 * catalog entry with a thin schema and remove it from here.
 *
 * Reasons:
 * - `personal`: carries or implies a person's details or messages (D21 keeps them off webhooks).
 * - `security`: risk, fraud, payouts, disputes deadlines and other signals only staff see.
 * - `workflow`: an internal step of a larger process (links, mailers, holds, projections).
 * - `platform`: the org's own account, domains, plan and team, not event data.
 * - `content`: CMS, media and site edits (the public content API serves the result).
 * - `later`: plausible public events kept back until a customer asks (additive when they do).
 */
export type InternalReason = 'personal' | 'security' | 'workflow' | 'platform' | 'content' | 'later';

export const INTERNAL_EVENTS: Readonly<Record<string, InternalReason>> = {
  'announcement.sent@1': 'later',
  'assistance.requested@1': 'personal',
  'assistance.updated@1': 'personal',
  'attendee.cancelled@1': 'later',
  'attendees.changed@1': 'workflow',
  'attendees.message_batch@1': 'personal',
  'automations.journey_step_failed@1': 'workflow',
  'billing.customer_linked@1': 'platform',
  'billing.entitlements_synced@1': 'platform',
  'billing.subscription_changed@1': 'platform',
  'bulk.completed@1': 'workflow',
  'bulk.requested@1': 'workflow',
  'bulk.undone@1': 'workflow',
  'campaign.opened@1': 'personal',
  'campaigns.send_completed@1': 'later',
  'campaigns.send_failed@1': 'workflow',
  'campaigns.send_started@1': 'later',
  'checkin.duplicate_offline@1': 'security',
  'checkin.fraud_signal@1': 'security',
  'cms.contact_requested@1': 'personal',
  'cms.entry_created@1': 'content',
  'cms.entry_deleted@1': 'content',
  'cms.help_article_created@1': 'content',
  'cms.help_article_deleted@1': 'content',
  'cms.site_section_changed@1': 'content',
  'crm.contacts_merged@1': 'personal',
  'crm.contacts_unmerged@1': 'personal',
  'device.enrolled@1': 'security',
  'device.heartbeat@1': 'security',
  'device.state_changed@1': 'security',
  'domain.activated@1': 'platform',
  'domain.added@1': 'platform',
  'domain.primary_changed@1': 'platform',
  'domain.removed@1': 'platform',
  'donations.charity_rejected@1': 'platform',
  'donations.charity_submitted@1': 'platform',
  'donations.charity_verified@1': 'platform',
  'donations.statement_issued@1': 'personal',
  'engagement.question_asked@1': 'personal',
  'engagement.vote_cast@1': 'workflow',
  'entitlements.changed@1': 'platform',
  'event.announcement_published@1': 'later',
  'event.occurrences_added@1': 'later',
  'event.occurrences_updated@1': 'later',
  'event.short_link_changed@1': 'content',
  'form.resume_requested@1': 'personal',
  'guests.invitation_queued@1': 'workflow',
  'guests.party_responded@1': 'personal',
  'guests.rsvp_deadline_set@1': 'workflow',
  'guests.rsvp_responded@1': 'personal',
  'integrations.connection_connected@1': 'platform',
  'integrations.connection_revoked@1': 'platform',
  'invitation.created@1': 'platform',
  'marketplace.site_settings_changed@1': 'platform',
  'media.asset_added@1': 'content',
  'media.asset_removed@1': 'content',
  'membership.added@1': 'platform',
  'messaging.auto_paused@1': 'platform',
  'messaging.delivery_problems@1': 'platform',
  'messaging.report_filed@1': 'personal',
  'order.checkout_blocked@1': 'security',
  'order.credit_note_issued@1': 'later',
  'order.donation_paid@1': 'later',
  'order.invoice_payment_recorded@1': 'later',
  'order.invoiced@1': 'later',
  'order.links_requested@1': 'personal',
  'order.manage_link_reissued@1': 'personal',
  'order.mass_refund_finished@1': 'later',
  'order.mass_refund_started@1': 'later',
  'order.payment_orphaned@1': 'security',
  'order.payment_started@1': 'workflow',
  'order.refund_request_declined@1': 'personal',
  'order.refund_requested@1': 'personal',
  'order.reserved@1': 'workflow',
  'order.risk_flagged@1': 'security',
  'order.support_reply@1': 'personal',
  'order.voided@1': 'later',
  'org.status_changed@1': 'platform',
  'org.suspension_changed@1': 'platform',
  'organization.created@1': 'platform',
  'organization.updated@1': 'platform',
  'payments.dispute_deadline_approaching@1': 'security',
  'payments.reconciliation_drift@1': 'security',
  'payouts.account_updated@1': 'security',
  'payouts.destination_changed@1': 'security',
  'payouts.hold_changed@1': 'security',
  'payouts.transferred@1': 'security',
  'portal.account_invited@1': 'personal',
  'privacy.subject_erased@1': 'personal',
  'program.booth.assigned@1': 'later',
  'program.exhibitor.staff_invited@1': 'personal',
  'program.exhibitor_deleted@1': 'later',
  'program.speaker_change.decided@1': 'later',
  'program.speaker_deleted@1': 'later',
  'program.speaker_task.assigned@1': 'workflow',
  'program.speaker_task.completed@1': 'workflow',
  'program.speaker_task.overdue@1': 'workflow',
  'program.speaker_task.reminder_requested@1': 'workflow',
  'program.sponsor_deleted@1': 'later',
  'registration.cell.disabled@1': 'workflow',
  'registration.cell.enabled@1': 'workflow',
  'registration.registrant.applied@1': 'later',
  'registration.registrant.approved@1': 'later',
  'registration.registrant.confirmed@1': 'later',
  'registration.registrant.denied@1': 'personal',
  'registration.registrant.substituted@1': 'personal',
  'registration.session.promoted@1': 'later',
  'registration.type.over_capacity@1': 'workflow',
  'review.hidden@1': 'later',
  'review.reported@1': 'personal',
  'review.unhidden@1': 'later',
  'seating.assignments_changed@1': 'later',
  'seating.finder_code_created@1': 'personal',
  'series.created@1': 'later',
  'session.attended@1': 'later',
  'survey.sent@1': 'workflow',
  'table.naming_link_requested@1': 'personal',
  'table.slot_named@1': 'personal',
  'thread.contact_wrote@1': 'personal',
  'thread.replied@1': 'personal',
  'ticket.admission_moved@1': 'later',
  'ticket.claim_link_created@1': 'personal',
  'ticket.holder_link_created@1': 'personal',
  'ticket.resend_requested@1': 'personal',
  'ticket.transfer_cancelled@1': 'workflow',
  'ticket.transfer_offered@1': 'personal',
  'venue.created@1': 'content',
  'venue.quote_requested@1': 'personal',
  'venue.updated@1': 'content',
  'waitlist.offer_expired@1': 'later',
  'waitlist.offer_released@1': 'later',
};
