import { identityDatabase } from '@yayatoh/db/identity';
import { uuidv7 } from '@yayatoh/kernel';
import { and, desc, eq, gt, isNull, lte } from 'drizzle-orm';
import { issueHandoff } from './handoff.ts';
import { impersonations, securityEvents, sessions } from './schema.ts';
import { getUsersByIds } from './users.ts';

/**
 * Staff impersonation (M1.2e, decision D14). Platform staff with the admin role act as an org
 * member for at most one hour, with a reason. The staff console starts it here and gets a
 * handoff code for the app host (M1.2d); the app host redeems it for a session that carries the
 * impersonation. Ending it (or the hour passing) deletes that session. The tenant audit rows are
 * written by the tenancy commands; this module keeps the global record and the security events.
 */
export const IMPERSONATION_MAX_MS = 60 * 60_000;
export const IMPERSONATION_REASON_MAX = 500;

export type ImpersonationEnd = 'ended' | 'expired' | 'revoked';

export interface Impersonation {
  readonly id: string;
  readonly staffUserId: string;
  readonly userId: string;
  readonly orgId: string;
  readonly reason: string;
  readonly returnUrl: string;
  readonly startedAt: Date;
  readonly expiresAt: Date;
  readonly endedAt: Date | null;
  readonly endedReason: string | null;
}

const COLUMNS = {
  id: impersonations.id,
  staffUserId: impersonations.staffUserId,
  userId: impersonations.userId,
  orgId: impersonations.orgId,
  reason: impersonations.reason,
  returnUrl: impersonations.returnUrl,
  startedAt: impersonations.startedAt,
  expiresAt: impersonations.expiresAt,
  endedAt: impersonations.endedAt,
  endedReason: impersonations.endedReason,
};

/** The reason as stored: trimmed, required, at most 500 characters (null if unusable). */
export function impersonationReason(raw: string | null | undefined): string | null {
  const r = (raw ?? '').replace(/\s+/g, ' ').trim();
  return r.length >= 1 && r.length <= IMPERSONATION_REASON_MAX ? r : null;
}

/** Open: not ended and inside its hour. */
export const isImpersonationActive = (i: Pick<Impersonation, 'endedAt' | 'expiresAt'>, now: Date) =>
  i.endedAt === null && i.expiresAt.getTime() > now.getTime();

async function record(userId: string, action: string, data: Record<string, unknown>, now: Date) {
  await identityDatabase()
    .insert(securityEvents)
    .values({ id: uuidv7(), userId, action, data, createdAt: now });
}

export interface StartImpersonationInput {
  /** Generated by the caller so the tenant audit row can name it before this row exists. */
  readonly id: string;
  readonly staffUserId: string;
  readonly userId: string;
  readonly orgId: string;
  readonly reason: string;
  /** The staff console page "End" returns to. */
  readonly returnUrl: string;
  readonly ipAddress?: string | null;
  /** The app host (redeems the code) and where to land there, e.g. `/o/{slug}`. */
  readonly appHost: string;
  readonly returnPath: string;
  readonly now?: Date;
}

/** Start one: the record, a security event for both people, and a handoff code for the app host. */
export async function startImpersonation(
  input: StartImpersonationInput,
): Promise<{ impersonation: Impersonation; code: string }> {
  const reason = impersonationReason(input.reason);
  if (!reason) throw new Error('An impersonation needs a reason');
  if (input.staffUserId === input.userId) throw new Error('Staff cannot impersonate themselves');
  const now = input.now ?? new Date();
  const [row] = await identityDatabase()
    .insert(impersonations)
    .values({
      id: input.id,
      staffUserId: input.staffUserId,
      userId: input.userId,
      orgId: input.orgId,
      reason,
      returnUrl: input.returnUrl,
      ipAddress: input.ipAddress ?? null,
      startedAt: now,
      expiresAt: new Date(now.getTime() + IMPERSONATION_MAX_MS),
    })
    .returning(COLUMNS);
  if (!row) throw new Error('Impersonation not recorded');
  const data = { impersonationId: row.id, orgId: row.orgId };
  await record(row.staffUserId, 'impersonation.started', { ...data, asUserId: row.userId }, now);
  await record(row.userId, 'impersonation.started_as_you', { ...data, byStaffUserId: row.staffUserId }, now);
  const { code } = await issueHandoff({
    userId: row.userId,
    host: input.appHost,
    returnPath: input.returnPath,
    impersonationId: row.id,
    now,
  });
  return { impersonation: row, code };
}

export async function getImpersonation(id: string): Promise<Impersonation | null> {
  const [row] = await identityDatabase()
    .select(COLUMNS)
    .from(impersonations)
    .where(eq(impersonations.id, id));
  return row ?? null;
}

/**
 * End one (idempotent): marks it ended and deletes its sessions. Returns the row if this call
 * ended it (so the caller writes the tenant audit row once), null if it had already ended.
 */
export async function endImpersonation(
  id: string,
  how: ImpersonationEnd,
  now: Date = new Date(),
): Promise<Impersonation | null> {
  const db = identityDatabase();
  const [row] = await db
    .update(impersonations)
    .set({ endedAt: now, endedReason: how })
    .where(and(eq(impersonations.id, id), isNull(impersonations.endedAt)))
    .returning(COLUMNS);
  await db.delete(sessions).where(eq(sessions.impersonationId, id));
  if (!row) return null;
  const data = { impersonationId: row.id, orgId: row.orgId, how };
  await record(row.staffUserId, 'impersonation.ended', data, now);
  await record(row.userId, 'impersonation.ended', data, now);
  return row;
}

/** Impersonations whose hour has passed but that nobody ended yet (the worker ends them). */
export async function dueImpersonations(now: Date = new Date(), limit = 100): Promise<Impersonation[]> {
  return identityDatabase()
    .select(COLUMNS)
    .from(impersonations)
    .where(and(isNull(impersonations.endedAt), lte(impersonations.expiresAt, now)))
    .limit(limit);
}

export interface ImpersonationListItem extends Impersonation {
  readonly staffName: string;
  readonly memberName: string;
  readonly memberEmail: string;
}

/** Recent impersonations in one org, newest first, with names (staff console only). */
export async function listImpersonations(orgId: string, limit = 20): Promise<ImpersonationListItem[]> {
  const rows = await identityDatabase()
    .select(COLUMNS)
    .from(impersonations)
    .where(eq(impersonations.orgId, orgId))
    .orderBy(desc(impersonations.startedAt))
    .limit(limit);
  const people = await getUsersByIds([...new Set(rows.flatMap((r) => [r.staffUserId, r.userId]))]);
  return rows.map((r) => ({
    ...r,
    staffName: people.get(r.staffUserId)?.name ?? '',
    memberName: people.get(r.userId)?.name ?? '',
    memberEmail: people.get(r.userId)?.email ?? '',
  }));
}

/** The staff member's open impersonations (to end one from the console). */
export async function openImpersonationsOf(staffUserId: string, now: Date = new Date()) {
  return identityDatabase()
    .select(COLUMNS)
    .from(impersonations)
    .where(
      and(
        eq(impersonations.staffUserId, staffUserId),
        isNull(impersonations.endedAt),
        gt(impersonations.expiresAt, now),
      ),
    );
}
