// M5.1d: print a badge with a balance due (audited override).
export { OVERRIDE_MINUTES, overrideAllows, overrideBalanceDueCommand } from './balance-override.ts';
export {
  BatchDto,
  type BatchRunDeps,
  type BatchSlice,
  badgePrintableTx,
  badgeTicketsQuery,
  batchFileByLink,
  batchFileKey,
  batchLinkQuery,
  batchPartsQuery,
  CHUNK_SIZE,
  cancelBatchCommand,
  failBatchCommand,
  finishBatchCommand,
  listBatchesQuery,
  MAX_BATCH_BADGES,
  nextBatchChunkCommand,
  oneBadgeHtmlTx,
  runBadgeBatch,
  singleBadgeQuery,
  startBatchCommand,
  storeBatchChunkCommand,
} from './batches.ts';
export * from './client.ts';
export { LINK_TTL_MS, signBatchLink, verifyBatchLink } from './link.ts';
export {
  type BadgePrinter,
  browserPrinter,
  devPrintNode,
  type FakePrinterState,
  type FakePrintNode,
  fakePrintNode,
  type PrintSubmission,
  printNodeFromEnv,
  printNodePrinter,
  type ReportedState,
  type SubmitResult,
} from './printer-port.ts';
export {
  archivePrinterCommand,
  BadgePrintStateDto,
  badgePrintStateQuery,
  browserJobBadgeQuery,
  createPrinterCommand,
  markQuietPrintersCommand,
  offlinePrinterCountTx,
  PRINTER_OFFLINE_EVENT,
  PRINTER_ONLINE_EVENT,
  PrinterDto,
  PrinterStatePayload,
  PrintingSetupDto,
  PrintJobDto,
  PrintLogEntryDto,
  pollPrintNodePrinters,
  printerHeartbeatCommand,
  printingSetupQuery,
  printLogQuery,
  recordPrinterStatesCommand,
  recordPrintResultCommand,
  type SendPrintDeps,
  sendPrintJob,
  setPrintNodeCommand,
  startPrintJobCommand,
  watchQuietPrinters,
} from './printing.ts';
export { privateColumns } from './private-columns.ts';
export { type BadgesHtmlInput, badgesHtml } from './render.ts';
export { samplePreviewQuery } from './sample.ts';
export { BATCH_STATUSES, type BatchStatus } from './schema.ts';
export {
  AssignmentDto,
  assignTemplateCommand,
  BadgeQuestionDto,
  BadgesSetupDto,
  badgeQuestionsTx,
  badgesSetupQuery,
  createTemplateCommand,
  deleteTemplateCommand,
  MAX_TEMPLATES_PER_EVENT,
  saveTemplateCommand,
  setDefaultTemplateCommand,
  TemplateDto,
} from './templates.ts';
