import {
  Armchair,
  Award,
  Bell,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarRange,
  ChartLine,
  ClipboardList,
  Copy,
  FileText,
  Globe,
  Heart,
  History,
  House,
  Image,
  KeyRound,
  Landmark,
  Layers,
  Library,
  ListChecks,
  Lock,
  type LucideIcon,
  MailCheck,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Palette,
  Scale,
  ScanLine,
  Search,
  Settings,
  ShieldCheck,
  Star,
  Store,
  Ticket,
  Users,
} from 'lucide-react';

/** Icon names used by the profiles registry (packages/platform/src/profiles). */
const ICONS: Record<string, LucideIcon> = {
  home: House,
  chart: ChartLine,
  'list-checks': ListChecks,
  palette: Palette,
  users: Users,
  ticket: Ticket,
  armchair: Armchair,
  megaphone: Megaphone,
  scan: ScanLine,
  library: Library,
  clipboard: ClipboardList,
  calendar: Calendar,
  store: Store,
  mic: Mic,
  award: Award,
  heart: Heart,
  message: MessageSquare,
  'mail-check': MailCheck,
  search: Search,
  globe: Globe,
  image: Image,
  'calendar-check': CalendarCheck,
  bell: Bell,
  settings: Settings,
  landmark: Landmark,
  scale: Scale,
  key: KeyRound,
  'calendar-range': CalendarRange,
  layers: Layers,
  copy: Copy,
  'map-pin': MapPin,
  'file-text': FileText,
  lock: Lock,
  building: Building2,
  history: History,
  shield: ShieldCheck,
  star: Star,
};

export function Icon({ name, className = 'size-4' }: { name: string; className?: string }) {
  const C = ICONS[name] ?? House;
  return <C aria-hidden="true" className={className} strokeWidth={1.6} />;
}
