/**
 * The words of the scheduled PDF report (M6.2b), in the 13 app locales. The PDF is rendered in
 * the worker for each recipient's language (the member's own locale), so it carries its own
 * catalogue like the notification templates do; `{org}`, `{period}`, `{date}` and `{timeZone}`
 * are filled by `fill`. Numbers, money and dates are formatted with `Intl` in the same locale.
 */
export interface ReportLabels {
  readonly subtitle: string;
  readonly meta: string;
  readonly registrations: string;
  readonly tickets: string;
  readonly compTickets: string;
  readonly refundedTickets: string;
  readonly checkins: string;
  readonly noShows: string;
  readonly revenue: string;
  readonly currency: string;
  readonly gross: string;
  readonly refunds: string;
  readonly net: string;
  readonly byDay: string;
  readonly day: string;
  readonly topEvents: string;
  readonly event: string;
  readonly empty: string;
  readonly footer: string;
  readonly footerFinance: string;
}

export const REPORT_LOCALES = [
  'en',
  'es',
  'fr',
  'de',
  'it',
  'pt',
  'nl',
  'ar',
  'hi',
  'ja',
  'ru',
  'zh-CN',
  'zh-TW',
] as const;
export type ReportLocale = (typeof REPORT_LOCALES)[number];
export const RTL_REPORT_LOCALES: ReadonlySet<string> = new Set(['ar']);

export const REPORT_LABELS: Readonly<Record<ReportLocale, ReportLabels>> = {
  en: {
    subtitle: '{org} · {period}',
    meta: 'Made {date} · Days in {timeZone}',
    registrations: 'Registrations',
    tickets: 'Tickets (net)',
    compTickets: 'Free tickets',
    refundedTickets: 'Refunded tickets',
    checkins: 'Check-ins',
    noShows: 'No-shows',
    revenue: 'Revenue',
    currency: 'Currency',
    gross: 'Gross',
    refunds: 'Refunds',
    net: 'Net',
    byDay: 'By day',
    day: 'Day',
    topEvents: 'Top events',
    event: 'Event',
    empty: 'Nothing in this period.',
    footer: 'Sent by Yayatoh for {org}.',
    footerFinance: 'Sent by Yayatoh for {org}. Revenue is before fees; currencies are never added together.',
  },
  es: {
    subtitle: '{org} · {period}',
    meta: 'Generado el {date} · Días en {timeZone}',
    registrations: 'Inscripciones',
    tickets: 'Entradas (netas)',
    compTickets: 'Entradas gratuitas',
    refundedTickets: 'Entradas reembolsadas',
    checkins: 'Registros de entrada',
    noShows: 'Ausencias',
    revenue: 'Ingresos',
    currency: 'Moneda',
    gross: 'Bruto',
    refunds: 'Reembolsos',
    net: 'Neto',
    byDay: 'Por día',
    day: 'Día',
    topEvents: 'Eventos principales',
    event: 'Evento',
    empty: 'Nada en este periodo.',
    footer: 'Enviado por Yayatoh para {org}.',
    footerFinance:
      'Enviado por Yayatoh para {org}. Ingresos antes de comisiones; las monedas nunca se suman.',
  },
  fr: {
    subtitle: '{org} · {period}',
    meta: 'Créé le {date} · Jours en {timeZone}',
    registrations: 'Inscriptions',
    tickets: 'Billets (nets)',
    compTickets: 'Billets gratuits',
    refundedTickets: 'Billets remboursés',
    checkins: 'Entrées',
    noShows: 'Absents',
    revenue: 'Revenus',
    currency: 'Devise',
    gross: 'Brut',
    refunds: 'Remboursements',
    net: 'Net',
    byDay: 'Par jour',
    day: 'Jour',
    topEvents: 'Événements principaux',
    event: 'Événement',
    empty: 'Rien sur cette période.',
    footer: 'Envoyé par Yayatoh pour {org}.',
    footerFinance:
      'Envoyé par Yayatoh pour {org}. Revenus avant frais ; les devises ne sont jamais additionnées.',
  },
  de: {
    subtitle: '{org} · {period}',
    meta: 'Erstellt am {date} · Tage in {timeZone}',
    registrations: 'Anmeldungen',
    tickets: 'Tickets (netto)',
    compTickets: 'Freitickets',
    refundedTickets: 'Erstattete Tickets',
    checkins: 'Check-ins',
    noShows: 'Nicht erschienen',
    revenue: 'Umsatz',
    currency: 'Währung',
    gross: 'Brutto',
    refunds: 'Erstattungen',
    net: 'Netto',
    byDay: 'Nach Tag',
    day: 'Tag',
    topEvents: 'Top-Events',
    event: 'Event',
    empty: 'Nichts in diesem Zeitraum.',
    footer: 'Gesendet von Yayatoh für {org}.',
    footerFinance:
      'Gesendet von Yayatoh für {org}. Umsatz vor Gebühren; Währungen werden nie zusammengezählt.',
  },
  it: {
    subtitle: '{org} · {period}',
    meta: 'Creato il {date} · Giorni in {timeZone}',
    registrations: 'Iscrizioni',
    tickets: 'Biglietti (netti)',
    compTickets: 'Biglietti gratuiti',
    refundedTickets: 'Biglietti rimborsati',
    checkins: 'Check-in',
    noShows: 'Assenti',
    revenue: 'Ricavi',
    currency: 'Valuta',
    gross: 'Lordo',
    refunds: 'Rimborsi',
    net: 'Netto',
    byDay: 'Per giorno',
    day: 'Giorno',
    topEvents: 'Eventi principali',
    event: 'Evento',
    empty: 'Niente in questo periodo.',
    footer: 'Inviato da Yayatoh per {org}.',
    footerFinance:
      'Inviato da Yayatoh per {org}. Ricavi al lordo delle commissioni; le valute non vengono mai sommate.',
  },
  pt: {
    subtitle: '{org} · {period}',
    meta: 'Gerado em {date} · Dias em {timeZone}',
    registrations: 'Inscrições',
    tickets: 'Ingressos (líquidos)',
    compTickets: 'Ingressos gratuitos',
    refundedTickets: 'Ingressos reembolsados',
    checkins: 'Check-ins',
    noShows: 'Ausências',
    revenue: 'Receita',
    currency: 'Moeda',
    gross: 'Bruto',
    refunds: 'Reembolsos',
    net: 'Líquido',
    byDay: 'Por dia',
    day: 'Dia',
    topEvents: 'Principais eventos',
    event: 'Evento',
    empty: 'Nada neste período.',
    footer: 'Enviado pela Yayatoh para {org}.',
    footerFinance: 'Enviado pela Yayatoh para {org}. Receita antes das taxas; moedas nunca são somadas.',
  },
  nl: {
    subtitle: '{org} · {period}',
    meta: 'Gemaakt op {date} · Dagen in {timeZone}',
    registrations: 'Registraties',
    tickets: 'Tickets (netto)',
    compTickets: 'Gratis tickets',
    refundedTickets: 'Terugbetaalde tickets',
    checkins: 'Check-ins',
    noShows: 'Niet verschenen',
    revenue: 'Omzet',
    currency: 'Valuta',
    gross: 'Bruto',
    refunds: 'Terugbetalingen',
    net: 'Netto',
    byDay: 'Per dag',
    day: 'Dag',
    topEvents: 'Topevenementen',
    event: 'Evenement',
    empty: 'Niets in deze periode.',
    footer: 'Verzonden door Yayatoh voor {org}.',
    footerFinance:
      'Verzonden door Yayatoh voor {org}. Omzet vóór kosten; valuta worden nooit bij elkaar opgeteld.',
  },
  ar: {
    subtitle: '{org} · {period}',
    meta: 'أُنشئ في {date} · الأيام بتوقيت {timeZone}',
    registrations: 'التسجيلات',
    tickets: 'التذاكر (الصافي)',
    compTickets: 'التذاكر المجانية',
    refundedTickets: 'التذاكر المستردة',
    checkins: 'تسجيلات الدخول',
    noShows: 'الغائبون',
    revenue: 'الإيرادات',
    currency: 'العملة',
    gross: 'الإجمالي',
    refunds: 'المبالغ المستردة',
    net: 'الصافي',
    byDay: 'حسب اليوم',
    day: 'اليوم',
    topEvents: 'أبرز الفعاليات',
    event: 'الفعالية',
    empty: 'لا شيء في هذه الفترة.',
    footer: 'أرسلته Yayatoh إلى {org}.',
    footerFinance: 'أرسلته Yayatoh إلى {org}. الإيرادات قبل الرسوم؛ ولا تُجمع العملات معًا أبدًا.',
  },
  hi: {
    subtitle: '{org} · {period}',
    meta: '{date} को बनाया गया · दिन {timeZone} समय क्षेत्र में',
    registrations: 'पंजीकरण',
    tickets: 'टिकट (शुद्ध)',
    compTickets: 'मुफ़्त टिकट',
    refundedTickets: 'रिफ़ंड किए गए टिकट',
    checkins: 'चेक-इन',
    noShows: 'अनुपस्थित',
    revenue: 'राजस्व',
    currency: 'मुद्रा',
    gross: 'सकल',
    refunds: 'रिफ़ंड',
    net: 'शुद्ध',
    byDay: 'दिन के अनुसार',
    day: 'दिन',
    topEvents: 'शीर्ष इवेंट',
    event: 'इवेंट',
    empty: 'इस अवधि में कुछ नहीं।',
    footer: 'Yayatoh द्वारा {org} के लिए भेजा गया।',
    footerFinance: 'Yayatoh द्वारा {org} के लिए भेजा गया। राजस्व शुल्क से पहले का है; मुद्राएँ कभी जोड़ी नहीं जातीं।',
  },
  ja: {
    subtitle: '{org} · {period}',
    meta: '{date} 作成 · 日付は {timeZone}',
    registrations: '申込数',
    tickets: 'チケット（純数）',
    compTickets: '無料チケット',
    refundedTickets: '返金済みチケット',
    checkins: 'チェックイン',
    noShows: '不参加',
    revenue: '売上',
    currency: '通貨',
    gross: '総額',
    refunds: '返金',
    net: '純額',
    byDay: '日別',
    day: '日付',
    topEvents: '上位のイベント',
    event: 'イベント',
    empty: 'この期間のデータはありません。',
    footer: '{org} 向けに Yayatoh から送信されました。',
    footerFinance: '{org} 向けに Yayatoh から送信されました。売上は手数料控除前で、通貨は合算しません。',
  },
  ru: {
    subtitle: '{org} · {period}',
    meta: 'Создано {date} · Дни по времени {timeZone}',
    registrations: 'Регистрации',
    tickets: 'Билеты (нетто)',
    compTickets: 'Бесплатные билеты',
    refundedTickets: 'Возвращённые билеты',
    checkins: 'Проходы',
    noShows: 'Неявки',
    revenue: 'Выручка',
    currency: 'Валюта',
    gross: 'Брутто',
    refunds: 'Возвраты',
    net: 'Нетто',
    byDay: 'По дням',
    day: 'День',
    topEvents: 'Лучшие события',
    event: 'Событие',
    empty: 'За этот период ничего нет.',
    footer: 'Отправлено Yayatoh для {org}.',
    footerFinance: 'Отправлено Yayatoh для {org}. Выручка до комиссий; валюты никогда не суммируются.',
  },
  'zh-CN': {
    subtitle: '{org} · {period}',
    meta: '生成于 {date} · 日期按 {timeZone}',
    registrations: '报名数',
    tickets: '门票（净数）',
    compTickets: '免费门票',
    refundedTickets: '已退款门票',
    checkins: '签到',
    noShows: '未到场',
    revenue: '收入',
    currency: '货币',
    gross: '总额',
    refunds: '退款',
    net: '净额',
    byDay: '按天',
    day: '日期',
    topEvents: '热门活动',
    event: '活动',
    empty: '此期间没有数据。',
    footer: '由 Yayatoh 为 {org} 发送。',
    footerFinance: '由 Yayatoh 为 {org} 发送。收入为扣除费用前金额；不同货币从不相加。',
  },
  'zh-TW': {
    subtitle: '{org} · {period}',
    meta: '產生於 {date} · 日期依 {timeZone}',
    registrations: '報名數',
    tickets: '票券（淨數）',
    compTickets: '免費票券',
    refundedTickets: '已退款票券',
    checkins: '報到',
    noShows: '未出席',
    revenue: '收入',
    currency: '貨幣',
    gross: '總額',
    refunds: '退款',
    net: '淨額',
    byDay: '按日',
    day: '日期',
    topEvents: '熱門活動',
    event: '活動',
    empty: '此期間沒有資料。',
    footer: '由 Yayatoh 為 {org} 傳送。',
    footerFinance: '由 Yayatoh 為 {org} 傳送。收入為扣除費用前金額；不同貨幣從不相加。',
  },
};

/** The report locale for a member's locale (`pt-BR` → `pt`, unknown → `en`). */
export function reportLocale(locale: string | null | undefined): ReportLocale {
  if (!locale) return 'en';
  if ((REPORT_LOCALES as readonly string[]).includes(locale)) return locale as ReportLocale;
  const lower = locale.toLowerCase();
  if (lower.startsWith('zh')) return /tw|hk|hant/.test(lower) ? 'zh-TW' : 'zh-CN';
  const base = lower.slice(0, 2);
  return (REPORT_LOCALES as readonly string[]).includes(base) ? (base as ReportLocale) : 'en';
}

export const fill = (template: string, values: Readonly<Record<string, string>>) =>
  template.replace(/\{(\w+)\}/g, (m, k: string) => values[k] ?? m);
