-- M3.11a: platform switches (open self-serve signup, default off) and onboarding progress.
-- Generated by drizzle-kit; the hand-written block below adds grants, the seed row and functions.
CREATE TABLE "platform"."flag_changes" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"key" text NOT NULL,
	"enabled" boolean NOT NULL,
	"changed_by" text NOT NULL,
	"reason" text NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "flag_changes_reason_length" CHECK (length(reason) between 3 and 500)
);
--> statement-breakpoint
CREATE TABLE "platform"."flags" (
	"key" text PRIMARY KEY NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"updated_by" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "flags_key_check" CHECK (key in ('open_signup'))
);
--> statement-breakpoint
CREATE TABLE "tenancy"."org_onboarding" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"org_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"signup_mode" text NOT NULL,
	"terms_at" timestamp with time zone,
	"privacy_at" timestamp with time zone,
	"brand_at" timestamp with time zone,
	"event_at" timestamp with time zone,
	"payouts_at" timestamp with time zone,
	"team_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"completed_by" text,
	CONSTRAINT "org_onboarding_org_id_id_key" UNIQUE("org_id","id"),
	CONSTRAINT "org_onboarding_signup_mode_check" CHECK (signup_mode in ('code', 'open', 'direct')),
	CONSTRAINT "org_onboarding_completed_check" CHECK ((completed_at is null) = (completed_by is null))
);
--> statement-breakpoint
ALTER TABLE "tenancy"."org_onboarding" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tenancy"."org_onboarding" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tenancy"."org_onboarding" ADD CONSTRAINT "org_onboarding_org_fk" FOREIGN KEY ("org_id") REFERENCES "tenancy"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "flag_changes_key_at_idx" ON "platform"."flag_changes" USING btree ("key","at");--> statement-breakpoint
CREATE INDEX "org_onboarding_org_id_idx" ON "tenancy"."org_onboarding" USING btree ("org_id");--> statement-breakpoint
CREATE UNIQUE INDEX "org_onboarding_org_key" ON "tenancy"."org_onboarding" USING btree ("org_id");--> statement-breakpoint
CREATE POLICY "org_onboarding_tenant_isolation" ON "tenancy"."org_onboarding" AS PERMISSIVE FOR ALL TO "app_user" USING (org_id = (SELECT NULLIF(current_setting('app.org_id', true), '')::uuid)) WITH CHECK (org_id = (SELECT NULLIF(current_setting('app.org_id', true), '')::uuid));--> statement-breakpoint
-- hand-written: begin
-- Platform switches (M3.11a). app_user has no privileges on either table: it reads a switch only
-- through platform.flag_enabled. Staff change a switch only through platform.set_flag
-- (platform_reader, audited in the access log by the caller), which records the change with its
-- reason. platform_reader keeps its default SELECT (the staff console shows the history).
REVOKE ALL ON platform.flags FROM app_user;--> statement-breakpoint
REVOKE ALL ON platform.flag_changes FROM app_user;--> statement-breakpoint
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON platform.flags FROM platform_reader;--> statement-breakpoint
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON platform.flag_changes FROM platform_reader;--> statement-breakpoint
-- Signup stays closed until the owner flips the switch (D28: the public launch waits for B-Y).
INSERT INTO platform.flags (key, enabled, updated_by) VALUES ('open_signup', false, 'migration')
ON CONFLICT (key) DO NOTHING;--> statement-breakpoint
CREATE FUNCTION platform.flag_enabled(p_key text)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog AS $$
  SELECT coalesce((SELECT f.enabled FROM platform.flags f WHERE f.key = p_key), false)
$$;
--> statement-breakpoint
-- Flip a switch. True when this call changed it (and wrote the history row); false when it was
-- already in that state. Unknown keys and a missing or over-long reason are refused.
CREATE FUNCTION platform.set_flag(p_key text, p_enabled boolean, p_by text, p_reason text)
RETURNS boolean
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = pg_catalog AS $$
DECLARE
  v_prev boolean;
BEGIN
  IF p_reason IS NULL OR length(btrim(p_reason)) NOT BETWEEN 3 AND 500 THEN
    RAISE EXCEPTION 'a reason of 3 to 500 characters is required' USING ERRCODE = '22023';
  END IF;
  IF p_by IS NULL OR length(btrim(p_by)) = 0 THEN
    RAISE EXCEPTION 'who changed the switch is required' USING ERRCODE = '22023';
  END IF;
  SELECT f.enabled INTO v_prev FROM platform.flags f WHERE f.key = p_key FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'unknown platform switch %', p_key USING ERRCODE = '22023';
  END IF;
  IF v_prev = p_enabled THEN
    RETURN false;
  END IF;
  UPDATE platform.flags f SET enabled = p_enabled, updated_by = left(p_by, 200), updated_at = now()
  WHERE f.key = p_key;
  INSERT INTO platform.flag_changes (key, enabled, changed_by, reason)
  VALUES (p_key, p_enabled, left(p_by, 200), btrim(p_reason));
  RETURN true;
END
$$;
--> statement-breakpoint
REVOKE ALL ON FUNCTION platform.flag_enabled(text) FROM PUBLIC;--> statement-breakpoint
REVOKE ALL ON FUNCTION platform.set_flag(text, boolean, text, text) FROM PUBLIC;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION platform.flag_enabled(text) TO app_user;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION platform.flag_enabled(text) TO platform_reader;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION platform.set_flag(text, boolean, text, text) TO platform_reader;
-- hand-written: end
