import { readFileSync, writeFileSync } from 'node:fs';
import openapiTS, { astToString } from 'openapi-typescript';

// `write` regenerates src/schema.ts from the committed apps/api/openapi.json; `check` fails if
// it is stale (a unit test runs the same check, so the SDK never drifts from the contract).
const spec = new URL('../../../apps/api/openapi.json', import.meta.url);
const out = new URL('../src/schema.ts', import.meta.url);

export async function generate(): Promise<string> {
  const ast = await openapiTS(JSON.parse(readFileSync(spec, 'utf8')), { alphabetize: true });
  return `/* Generated by \`pnpm --filter @yayatoh/sdk generate\` from apps/api/openapi.json. Do not edit. */\n\n${astToString(ast)}`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const next = await generate();
  if (process.argv[2] === 'write') {
    writeFileSync(out, next);
    console.info('src/schema.ts written');
  } else {
    let current = '';
    try {
      current = readFileSync(out, 'utf8');
    } catch {}
    if (current !== next) {
      console.error('packages/sdk/src/schema.ts is stale. Run `pnpm --filter @yayatoh/sdk generate`.');
      process.exit(1);
    }
    console.info('src/schema.ts is up to date');
  }
}
