import type { MessageKind } from '../kinds.ts';

/** Sample params per kind: previews in the console and the 13-locale snapshot tests. */
export const SAMPLE_PARAMS: Readonly<Record<MessageKind, Readonly<Record<string, string | number>>>> = {
  'orders.tickets': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    count: 2,
  },
  'orders.refund': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    amountMinor: 4500,
    currency: 'USD',
    fully: 'no',
  },
  'events.reminder': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    startsAt: '2027-06-12T23:30:00.000Z',
    timeZone: 'America/Chicago',
    venue: 'Harbor Hall',
  },
  'tenancy.invitation': {
    url: 'https://app.yayatoh.test/invite/sample',
    role: 'manager',
    orgName: 'Lakeside Events',
  },
  'ticketing.claim-link': { url: 'https://app.yayatoh.test/claim/sample', eventName: 'Lakeside Jazz Night' },
  'ticketing.holder-link': {
    url: 'https://app.yayatoh.test/my-tickets/sample',
    eventName: 'Lakeside Jazz Night',
  },
  'ticketing.tickets-resent': {
    url: 'https://app.yayatoh.test/my-tickets/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    code: 'K7M2Q9XW',
  },
  'ticketing.ticket-cancelled': { name: 'Amina Diallo', eventName: 'Lakeside Jazz Night', code: 'K7M2Q9XW' },
  'seating.finder-code': {
    code: '482913',
    eventName: 'Lakeside Jazz Night',
    url: 'https://app.yayatoh.test/events/lakeside-jazz-night/seat-finder',
    minutes: 10,
  },
  'guest.checkout-code': { code: '305117', minutes: 10 },
  'guest.sign-in': {
    code: '305117',
    url: 'https://app.yayatoh.test/my-tickets/verify/sample',
    minutes: 10,
    linkMinutes: 15,
    site: 'Lakeside Events',
  },
  'orders.order-link': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    reason: 'resend',
  },
  'attendees.message': {
    subject: 'Parking update',
    body: 'Lot B is closed tonight.\nPlease use Lot C on Harbor Street.',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
  },
  'messaging.announcement': {
    subject: 'Doors open at 7',
    body: 'We open doors 30 minutes early.\n\nSee you soon!',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    replyUrl: 'https://app.yayatoh.test/messages/sample',
  },
  'messaging.reply': {
    body: 'Yes, the venue is step-free.',
    name: 'Amina Diallo',
    replyUrl: 'https://app.yayatoh.test/messages/sample',
  },
  'security.fraud_signal': { signal: 'purchase_velocity', eventName: 'Lakeside Jazz Night' },
  'sales.order_paid': {
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    count: 2,
    amountMinor: 9000,
    currency: 'USD',
  },
  'messaging.contact_replied': { name: 'Amina Diallo', eventName: 'Lakeside Jazz Night' },
  'payments.destination-changed': {
    url: 'https://app.yayatoh.test/o/lakeside-events/payouts',
    reason: 'connected',
    holdUntil: '2027-06-13T15:00:00.000Z',
    timeZone: 'America/Chicago',
  },
  'tenancy.staff-access': {
    url: 'https://app.yayatoh.test/o/lakeside-events/activity',
    member: 'Jordan Lee',
    reason: 'Support ticket 4312: the organizer asked for help with seating',
    until: '2027-06-12T16:00:00.000Z',
    timeZone: 'America/Chicago',
  },
  'tenancy.org-status': { url: 'https://app.yayatoh.test/o/lakeside-events', status: 'suspended' },
  'notifications.test': {},
};
