import type { MessageKind } from '../kinds.ts';

/** Sample params per kind: previews in the console and the 13-locale snapshot tests. */
export const SAMPLE_PARAMS: Readonly<Record<MessageKind, Readonly<Record<string, string | number>>>> = {
  'orders.tickets': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    count: 2,
  },
  'orders.refund': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    amountMinor: 4500,
    currency: 'USD',
    fully: 'no',
  },
  'orders.refund-requested': { name: 'Amina Diallo', eventName: 'Lakeside Jazz Night', count: 2 },
  'orders.refund-declined': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    reason: 'The refund window closed a week before the event.',
  },
  'orders.credit-note': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    number: 'CN-00007',
    amountMinor: 2500,
    currency: 'USD',
    storeCredit: 'yes',
    code: 'CR-7KQ4-MX2P',
  },
  'orders.support-reply': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    subject: 'Your tickets for Lakeside Jazz Night',
    body: 'Hi Amina, we sent your tickets again.\n\nSee you at the show!',
  },
  'payments.dispute-deadline': {
    eventName: 'Lakeside Jazz Night',
    amountMinor: 4500,
    currency: 'USD',
    hours: 20,
  },
  'ticketing.transfer-offered': {
    url: 'https://app.yayatoh.test/claim/sample',
    name: 'Noor Haddad',
    fromName: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
  },
  'ticketing.transfer-completed': {
    name: 'Amina Diallo',
    toName: 'Noor Haddad',
    eventName: 'Lakeside Jazz Night',
  },
  'ticketing.transfer-received': {
    url: 'https://app.yayatoh.test/my-tickets/sample',
    name: 'Noor Haddad',
    fromName: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
  },
  'events.postponed': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
  },
  'events.reminder': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    startsAt: '2027-06-12T23:30:00.000Z',
    timeZone: 'America/Chicago',
    venue: 'Harbor Hall',
  },
  'tenancy.invitation': {
    url: 'https://app.yayatoh.test/invite/sample',
    role: 'manager',
    orgName: 'Lakeside Events',
  },
  'tenancy.event-invitation': {
    url: 'https://app.yayatoh.test/invite/sample',
    role: 'planner',
    orgName: 'Lakeside Events',
    eventName: 'Amina & Tomas',
  },
  'ticketing.claim-link': { url: 'https://app.yayatoh.test/claim/sample', eventName: 'Lakeside Jazz Night' },
  'ticketing.holder-link': {
    url: 'https://app.yayatoh.test/my-tickets/sample',
    eventName: 'Lakeside Jazz Night',
  },
  'ticketing.tickets-resent': {
    url: 'https://app.yayatoh.test/my-tickets/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    code: 'K7M2Q9XW',
  },
  'ticketing.ticket-cancelled': { name: 'Amina Diallo', eventName: 'Lakeside Jazz Night', code: 'K7M2Q9XW' },
  'seating.finder-code': {
    code: '482913',
    eventName: 'Lakeside Jazz Night',
    url: 'https://app.yayatoh.test/events/lakeside-jazz-night/seat-finder',
    minutes: 10,
  },
  'guest.checkout-code': { code: '305117', minutes: 10 },
  'portal.invite': {
    url: 'https://app.yayatoh.test/event-portal/invite/sample',
    eventName: 'Midwest Leadership Summit',
    role: 'speaker',
  },
  'portal.sign-in': {
    code: '305117',
    url: 'https://app.yayatoh.test/event-portal/verify/sample',
    minutes: 10,
    linkMinutes: 15,
    eventName: 'Midwest Leadership Summit',
  },
  'program.task-reminder': {
    url: 'https://app.yayatoh.test/event-portal/invite/sample',
    eventName: 'Midwest Leadership Summit',
    title: 'Upload your slides',
    until: '2027-05-10T17:00:00.000Z',
    timeZone: 'America/Chicago',
  },
  'guest.sign-in': {
    code: '305117',
    url: 'https://app.yayatoh.test/my-tickets/verify/sample',
    minutes: 10,
    linkMinutes: 15,
    site: 'Lakeside Events',
  },
  'guest.waitlist-code': { code: '305117', minutes: 10, eventName: 'Lakeside Jazz Night' },
  'forms.resume': {
    url: 'https://app.yayatoh.test/registration-form/sample',
    name: 'Amina Diallo',
    eventName: 'Midwest Leadership Summit',
    days: 14,
  },
  'orders.waitlist-joined': {
    url: 'https://app.yayatoh.test/waitlist/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    passName: 'General Admission',
    count: 2,
    position: 3,
  },
  'orders.waitlist-offer': {
    url: 'https://app.yayatoh.test/waitlist/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    passName: 'General Admission',
    count: 2,
    until: '2027-10-13T23:00:00.000Z',
    timeZone: 'America/Chicago',
  },
  'orders.waitlist-expired': {
    url: 'https://app.yayatoh.test/waitlist/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    passName: 'General Admission',
  },
  'orders.order-link': {
    url: 'https://app.yayatoh.test/orders/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    reason: 'resend',
  },
  'attendees.message': {
    subject: 'Parking update',
    body: 'Lot B is closed tonight.\nPlease use Lot C on Harbor Street.',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
  },
  'messaging.announcement': {
    subject: 'Doors open at 7',
    body: 'We open doors 30 minutes early.\n\nSee you soon!',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    replyUrl: 'https://app.yayatoh.test/messages/sample',
  },
  'messaging.reply': {
    body: 'Yes, the venue is step-free.',
    name: 'Amina Diallo',
    replyUrl: 'https://app.yayatoh.test/messages/sample',
  },
  'security.fraud_signal': { signal: 'purchase_velocity', eventName: 'Lakeside Jazz Night' },
  'surveys.invite': {
    url: 'https://app.yayatoh.test/survey/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    title: 'How was Lakeside Jazz Night?',
  },
  'surveys.reminder': {
    url: 'https://app.yayatoh.test/survey/sample',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    title: 'How was Lakeside Jazz Night?',
  },
  'sales.order_paid': {
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
    count: 2,
    amountMinor: 9000,
    currency: 'USD',
  },
  'messaging.contact_replied': { name: 'Amina Diallo', eventName: 'Lakeside Jazz Night' },
  'payments.destination-changed': {
    url: 'https://app.yayatoh.test/o/lakeside-events/payouts',
    reason: 'connected',
    holdUntil: '2027-06-13T15:00:00.000Z',
    timeZone: 'America/Chicago',
  },
  'tenancy.staff-access': {
    url: 'https://app.yayatoh.test/o/lakeside-events/activity',
    member: 'Jordan Lee',
    reason: 'Support ticket 4312: the organizer asked for help with seating',
    until: '2027-06-12T16:00:00.000Z',
    timeZone: 'America/Chicago',
  },
  'tenancy.org-status': { url: 'https://app.yayatoh.test/o/lakeside-events', status: 'suspended' },
  'campaigns.test': { subject: 'Early-bird tickets are back' },
  'guests.invitation': {
    url: 'https://app.yayatoh.test/rsvp/sample-token',
    subject: "You're invited: Lopez Chen Wedding",
    message:
      'Dear The Garcia family,\n\nWe would love to celebrate Lopez Chen Wedding with you. Please let us know who of your household can come.',
    eventName: 'Lopez Chen Wedding',
  },
  'guests.rsvp-reminder': {
    url: 'https://app.yayatoh.test/rsvp/sample-token',
    name: 'The Garcia family',
    eventName: 'Lopez Chen Wedding',
    deadline: 'May 1, 2027',
  },
  'automations.message': {
    subject: 'One week to go',
    body: 'Lakeside Jazz Night is next Friday. Doors open at 7 pm.',
    name: 'Amina Diallo',
    eventName: 'Lakeside Jazz Night',
  },
  'marketing.message': {
    subject: 'Early-bird tickets are back',
    body: 'Save 20% on the autumn season until Friday.',
    name: 'Amina Diallo',
  },
  'messaging.auto_paused': { rateBps: 42 },
  'alerts.alert': { rule: 'unseated', count: 37, severity: 'warning', eventName: 'Lakeside Jazz Night' },
  'alerts.alert-text': {
    rule: 'devicesOffline',
    count: 3,
    severity: 'critical',
    eventName: 'Lakeside Jazz Night',
  },
  'notifications.test': {},
};
