/** Module keys with a label (`privacy.modules.*`); others show their key (M6.1c; shared by server and client). */
export const PRIVACY_MODULES = [
  'crm',
  'orders',
  'ticketing',
  'attendees',
  'forms',
  'checkin',
  'tenancy',
  'notifications',
  'seating',
  'alerts',
  'guests',
  'messaging',
  'assistance',
  'program',
  'events',
  'media',
  'cms',
  'venues',
  'reviews',
  'payments',
  'surveys',
  'registration',
  'donations',
  'engagement',
  'badges',
  'automations',
  'campaigns',
  'audiences',
  'marketing',
  'reports',
  'privacy',
  'platform',
] as const;
